import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/components/layout/Layout";
import Providers from "@/providers/Providers";
import { getServerSettings, type ServerSettings } from "@/app/api/_lib/settingsServer";
import { buildThemeStyleCSS } from "@/shared/lib/theme";
import type { Design, General } from "@/features/settings/types";

type AppSettings = ServerSettings;

const resolveGeneralSettings = (settings: ServerSettings | null) => {
	const raw = settings?.general as Record<string, unknown> | undefined;
	if (!raw || typeof raw !== "object") return { general: undefined, design: undefined };
	const nestedGeneral = (raw as { general?: unknown }).general;
	const general =
		nestedGeneral && typeof nestedGeneral === "object"
			? (nestedGeneral as Record<string, unknown>)
			: ("primaryColor" in raw ||
				"secondaryColor" in raw ||
				"title" in raw ||
				"logoType" in raw
					? raw
					: undefined);
	const design = (raw as { design?: unknown }).design as Record<string, unknown> | undefined;
	return { general, design };
};

const buildThemeStyle = (settings: ServerSettings | null) => {
	const { general, design } = resolveGeneralSettings(settings);
	// CSS 변수 매핑은 shared/lib/theme.ts가 단일 소스 (클라이언트 ThemeProvider와 공유)
	return buildThemeStyleCSS(
		design as Partial<Design> | undefined,
		general as Partial<General> | undefined
	);
};

const getPreloadImageUrls = (settings: AppSettings | null) => {
	if (!settings) return [];

	const backgroundImage =
		settings.general?.design?.background?.type === "이미지" ?
			settings.general?.design?.background?.image :
			undefined;
	const menuDesign = settings.general?.menu?.design;

	const urls = [
		backgroundImage,
		menuDesign?.backgroundImage,
		menuDesign?.iconBarBackgroundImage,
		menuDesign?.logoImage,
		menuDesign?.iconBarLogoImage,
	];

	return Array.from(
		new Set(urls.filter((url): url is string => !!url))
	);
};

const getSettings = getServerSettings;

export async function generateMetadata(): Promise<Metadata> {
	const settings = await getSettings();
	const title = settings?.general?.general?.title || "Create Next App";
	const description = settings?.general?.general?.desc || "Generated by create next app";
	const shareImage = settings?.general?.general?.shareImage;

	const favicon = settings?.general?.general?.favicon;

	const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? process.env.NEXT_PUBLIC_BASE_URL ?? "";

	return {
		...(siteUrl && { metadataBase: new URL(siteUrl) }),
		title,
		description,
		icons: {
			icon: favicon || "/favicon.ico",
		},
		openGraph: {
			title,
			description,
			...(shareImage && {
				images: [
					{
						url: shareImage,
						width: 1200,
						height: 630,
						alt: title,
					},
				],
			}),
		},
		twitter: {
			card: "summary_large_image",
			title,
			description,
			...(shareImage && {
				images: [
					{
						url: shareImage,
						width: 1200,
						height: 630,
						alt: title,
					},
				],
			}),
		},
	};
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const settings = await getSettings();
	const themeStyle = buildThemeStyle(settings);
	const preloadImages = getPreloadImageUrls(settings);

	return (
		<html lang="en">
			<head>
				<link rel="preconnect" href="https://cdn.jsdelivr.net" crossOrigin="anonymous" />
				{/* dynamic-subset: unicode-range로 분할되어 실제 사용 글리프 청크만
				    내려받는다 — static 전체 웨이트(수백 KB~MB) 대비 전송량 대폭 감소.
				    preload로 CSS 페치를 HTML 파싱과 동시에 시작한다. */}
				<link
					rel="preload"
					as="style"
					href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard-dynamic-subset.min.css"
				/>
				<link
					rel="stylesheet"
					href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard-dynamic-subset.min.css"
				/>
				{preloadImages.map((url) => (
					<link key={url} rel="preload" as="image" href={url} />
				))}
				{/* 폰트 레지스트리 <link>/<style>은 ThemeProvider(FontRegistryAssets)가
				    SSR 포함 전 구간에서 렌더링한다. 여기서 중복 렌더링하면 소유권이 갈라진다. */}
				{themeStyle ? <style>{themeStyle}</style> : null}
			</head>
			<body>
				<Providers initialSettings={settings}>
					<Layout>{children}</Layout>
				</Providers>
			</body>
		</html>
	);
}
