import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/components/layout/Layout";
import Providers from "@/providers/Providers";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

async function getSettings() {
	try {
		const res = await fetch("https://api-w5buphcleq-du.a.run.app/settings", {
			cache: "force-cache",
			next: { revalidate: 3600 },
		});

		if (!res.ok) {
			console.error(`API 오류: ${res.status} - ${res.statusText}`);
			return null;
		}

		const data = await res.json();
		console.log("설정 데이터:", data);
		return data;
	} catch (error) {
		console.error("설정 로드 실패:", error);
		return null;
	}
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const settings = await getSettings();
	return (
		<html lang="en">
			<head>
				<link
					rel="preconnect"
					href="https://cdn.jsdelivr.net"
				/>
				<link
					rel="stylesheet"
					href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css"
				/>
			</head>
			<body>
				<Providers initialSettings={settings}>
					<Layout>{children}</Layout>
				</Providers>
			</body>
		</html>
	);
}
