import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/components/layout/Layout";
import Providers from "@/providers/Providers";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const SETTINGS_REVALIDATE_SECONDS = 60 * 60;

type ThemeSettings = {
	general?: {
		general?: {
			primaryColor?: string;
			secondaryColor?: string;
		};
		design?: {
			font?: {
				bodyFontFamily?: string;
				titleFontFamily?: string;
				mainFontColor?: string;
				subFontColor?: string;
			};
			background?: {
				type?: string;
				color?: string;
				image?: string;
			};
			widget?: {
				background?: string;
				borderColor?: string;
				borderRadius?: number;
				borderWidth?: number;
				blur?: number;
			};
			card?: {
				background?: string;
				borderColor?: string;
				borderActiveColor?: string;
				borderRadius?: number;
				boxShadow?: string;
				translateY?: number;
			};
		};
	};
};

const buildThemeStyle = (settings: ThemeSettings | null) => {
	const general = settings?.general?.general;
	const design = settings?.general?.design;
	if (!general || !design) return "";

	const variables = [
		`--primary-color:${general.primaryColor ?? "#007bff"}`,
		`--secondary-color:${general.secondaryColor ?? "#6c757d"}`,
		`--font-body:${design.font?.bodyFontFamily ?? "sans-serif"}`,
		`--font-title:${design.font?.titleFontFamily ?? "sans-serif"}`,
		`--color-main:${design.font?.mainFontColor ?? "#111111"}`,
		`--color-sub:${design.font?.subFontColor ?? "#666666"}`,
		`--bg-color:${design.background?.color ?? "#ffffff"}`,
		`--widget-bg:${design.widget?.background ?? "rgba(255,255,255,0.8)"}`,
		`--widget-border-color:${design.widget?.borderColor ?? "rgba(0,0,0,0.1)"}`,
		`--widget-border-radius:${design.widget?.borderRadius ?? 16}px`,
		`--widget-border-width:${design.widget?.borderWidth ?? 1}px`,
		`--widget-border-style:solid`,
		`--widget-blur:${design.widget?.blur ?? 0}px`,
		`--card-bg:${design.card?.background ?? "rgba(255,255,255,0.9)"}`,
		`--card-border-color:${design.card?.borderColor ?? "rgba(0,0,0,0.08)"}`,
		`--card-border-active:${design.card?.borderActiveColor ?? "rgba(0,0,0,0.2)"}`,
		`--card-border-radius:${design.card?.borderRadius ?? 20}px`,
		`--card-border-style:solid`,
		`--card-shadow:${design.card?.boxShadow ?? "none"}`,
		`--card-translate-y:${design.card?.translateY ?? 0}px`,
	];

	if (design.background?.type === "이미지" && design.background?.image) {
		variables.push(`--bg-image:url("${design.background.image}")`);
	}

	return `:root{${variables.join(";")}}`;
};

async function getSettings() {
	try {
		const res = await fetch("https://api-w5buphcleq-du.a.run.app/settings", {
			next: { revalidate: SETTINGS_REVALIDATE_SECONDS },
		});

		if (!res.ok) {
			return null;
		}

		const data = await res.json();
		return data;
	} catch {
		return null;
	}
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const settings = await getSettings();
	const themeStyle = buildThemeStyle(settings);
	return (
		<html lang="en">
			<head>
				<link rel="preconnect" href="https://cdn.jsdelivr.net" />
				<link
					rel="stylesheet"
					href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css"
				/>
				{themeStyle ? <style>{themeStyle}</style> : null}
			</head>
			<body>
				<Providers initialSettings={settings}>
					<Layout>{children}</Layout>
				</Providers>
			</body>
		</html>
	);
}
